def error(s):
    'Other error encountered -- print error message and exit.'
    print ''
    print ('ERROR: ' + s)
    print ''
    usage()
