{
  try {
    f.get();
  }
 catch (  CancellationException ex) {
  }
catch (  Throwable t) {
    if (_ex == null)     _ex=t instanceof ExecutionException ? t.getCause() : t;
  }
}
