{
  if (!_firstException.getAndSet(true)) {
    _dt.setException(ex);
    onCompletion(caller);
  }
  return false;
}
